const data = [
    { id: 1, 
    nama: "Mangga", 
    jenis: "Pohon", 
    warna: "Hijau", 
    },
    { id: 2, 
        nama: "Mawar", 
        jenis: "Bunga", 
        warna: "Merah", 
    },
    { id: 3, 
        nama: "Alang-alang", 
        jenis: "Rumput", 
        warna: "Kuning",  
    },
    { id: 4, 
        nama: "Pohon Cemara", 
        jenis: "Semak", 
        warna: "Hijau", 
    },
    { id: 5, 
        nama: "Pakis", 
        enis: "Paku", 
        warna: "Hijau", 
    },
    { id: 6, 
        nama: "Kaktus", 
        jenis: "Kaktus", 
        warna: "Hijau",  
    }
  ];
  
  export default data;
  